# Generated by Django 3.1.3 on 2020-12-30 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivento', '0005_auto_20201230_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='items_json',
            new_name='items_Ivento',
        ),
    ]
