# Generated by Django 3.1.3 on 2020-12-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivento', '0006_auto_20201230_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default='', max_length=70),
        ),
    ]
