# Generated by Django 3.1.3 on 2021-01-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ivento', '0009_auto_20210108_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
    ]
